Labs/Lab3/Controllers/MVCHotelController.cs
using Microsoft.AspNetCore.Mvc;
using Lab3.Models;

namespace Lab3.Controllers
{
    public class MVCHotelController : Controller
    {
        public IActionResult Index()
        {
            List<Room> rooms = Hotel.Rooms;
            return View(rooms);
        }

        public IActionResult Capacity()
        {
            ViewBag.Remaining = Hotel.GetVacantRooms().Count;
            IEnumerable<Room> rooms = Hotel.Rooms;
            return View(rooms);
        }

        public IActionResult Room(int occupants)
        {
            if(occupants > 6)
            {
                ViewBag.Message = "Sorry! There is no room available.";
                return View();
            }
            else
            {
                ViewBag.Message = null;
                Room room = (from ro in Hotel.Rooms
                             where (ro.Occupied == false & ro.Capacity >= occupants)
                             select ro).ToList()[0];
                return View(room);
            }         
        }
    }
}

Labs/Lab3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCHotel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="MVCHotel" asp-action="Index">MVCHotel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MVCHotel" asp-action="Capacity">Capacity</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MVCHotel" asp-action="Room">Room</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCHotel - <a asp-area="" asp-controller="MVCHotel" asp-action="Index">Homepage</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>